
parameters:
  num_iterations: [8]
  device: [cuda]
  lr: [0.05]
  val_num_samples: [5000]
  val_fold_idx: [0, 1, 2, 3]
  model: [dcama_ada]
  n_ways: [1]
  k_shots: [5]
  peft_type: ["full"]
  subsample: [1]
  target_modules: [["adapter_blocks"]]

other_grids:
