#!/bin/bash

#SBATCH -A IscrC_MOSES
#SBATCH -p boost_usr_prod
#SBATCH --qos normal
#SBATCH --time=24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --mem=0
#SBATCH --exclusive
#SBATCH --job-name=TaP
#SBATCH --out=out/lora.log
#SBATCH --err=out/lora.log

srun ./slurm/launch_lora_multi_gpu_exe $@
