#!/bin/bash

export HF_HOME=$SCRATCH
export TORCH_HOME=$SCRATCH

echo "HF_HOME: $HF_HOME"
echo "TORCH_HOME: $TORCH_HOME"

conda init zsh
conda activate label-anything
export TMPDIR=./tmp
python main.py $@
