#!/bin/bash

#SBATCH -A IscrC_ARTURO
#SBATCH -p boost_usr_prod
#SBATCH --qos normal
#SBATCH --time=24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=123000
#SBATCH --job-name=TaP
#SBATCH --out=out/lora.log
#SBATCH --err=out/lora.log
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=pasquale.demarinis@uniba.it

srun ./slurm/launch_lora_exe $@
