experiment:
  group: ISIC
parameters:
  # num_iterations: [8, 16, 24]
  num_iterations: [8]
  device: [cuda]
  lora_r: [64]
  lr: [0.0001]
  target_modules: ["^backbone\\..*\\.conv1$"]
  lora_dropout: [0.1]
  val_num_samples: [1200]
  model: [dmtnet]
  n_ways: [1]
  k_shots: [3]
  subsample: [1]
  dataset: [isic]

other_grids:
