
parameters:
  dataset: [coco]
  num_iterations: [10]
  device: [cuda]
  # lora_r: [8, 16, 32, 128, 256, 512, 1024]
  lora_r: [8, 16, 32]
  lr: [0.001]
  target_modules: ["qkv,"]
  lora_dropout: [0.1]
  val_num_samples: [1000]
  val_fold_idx: [0]
  model: [dcama]
  n_ways: [2]
  k_shots: [5]

other_grids:
