experiment:
  group: Computation

parameters:
  computation_test: [True]

  dataset: [coco]
  device: [cuda:1]
  lr: [0.001]
  val_fold_idx: [0]
  model: [fptrans_ada]
  target_modules: [["adapter_block"]]
  n_ways: [1]
  k_shots: [1, 5]
  lora: [False]

other_grids:

