experiment:
  group: Computation

parameters:
  computation_test: [True]

  dataset: [coco]
  device: [cuda]
  peft_type: [lora]
  lora_r: [64]
  lr: [0.001]
  target_modules: ["query,value"]
  val_fold_idx: [0]
  model: [label_anything]
  n_ways: [1]
  k_shots: [1, 5]

other_grids:

